/* constants */
const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
const BEGIN_PROMISE_CALL = 'BEGIN_PROMISE_CALL';
const FINISH_PROMISE_CALL = 'FINISH_PROMISE_CALL';
const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';

export {
	LOAD_COURSES_SUCCESS,
	LOAD_AUTHORS_SUCCESS,
	UPDATE_COURSE_SUCCESS,
	CREATE_COURSE_SUCCESS,
	BEGIN_PROMISE_CALL,
	FINISH_PROMISE_CALL,
	DELETE_COURSE_SUCCESS
};
